# -*- coding: utf-8 -*-
"""Actividad2Simu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12c2-4wR1oaOAmQNMJGOQqBZ8BUTraL_y
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

class MantenimientoHMM:
    def __init__(self):
        self.estados = ['Normal', 'Desgaste', 'Falla']
        self.obs_nombres = ['Baja', 'Media', 'Alta']

        # 1. Especificaciones del Modelo
        self.pi = np.array([0.80, 0.15, 0.05])
        self.transicion = np.array([
            [0.85, 0.13, 0.02],#normal
            [0.30, 0.50, 0.20],#desgaste
            [0.05, 0.15, 0.80]#falla
        ])
        self.emision = np.array([ ## el sensor
            [0.80, 0.15, 0.05],#normal
            [0.30, 0.50, 0.20],#desgaste
            [0.10, 0.30, 0.60]#falla
        ])

    def generar_hz(self, obs_idx):
        # Mapeo de categorías a valores continuos de Hz
        rangos = [(10, 30), (35, 65), (70, 110)]#bajo(10, 30) #media(35, 65) #alta(70, 110)
        return np.random.uniform(rangos[obs_idx][0], rangos[obs_idx][1])

    def simular(self, n_pasos=60):
        historial_estados = []
        historial_obs = []
        vibracion_hz = []

        estado_actual = np.random.choice([0, 1, 2], p=self.pi)

        for _ in range(n_pasos):
            obs_idx = np.random.choice([0, 1, 2], p=self.emision[estado_actual])
            historial_estados.append(estado_actual)
            historial_obs.append(obs_idx)
            vibracion_hz.append(self.generar_hz(obs_idx))

            estado_actual = np.random.choice([0, 1, 2], p=self.transicion[estado_actual])

        return pd.DataFrame({
            'Hora': range(1, n_pasos + 1),
            'Estado_Real': historial_estados,
            'Obs_Idx': historial_obs,
            'Vibracion_Hz': vibracion_hz
        })

# --- EJECUCIÓN Y MÉTRICAS ---
modelo = MantenimientoHMM()
df = modelo.simular(60)

# Calcular RUL (Vida Útil Restante estimada simplificada)
# Si la tasa de falla es 0.02 en normal, la vida media es 1/p
mtbf_estimado = 1 / 0.15 # Probabilidad de salir de estado Normal/Estable
falla_detectada = df[df['Estado_Real'] == 2]['Hora'].min()
rul = falla_detectada - df['Hora'].max() if not pd.isna(falla_detectada) else mtbf_estimado

# --- DASHBOARD INDUSTRIAL ---
plt.style.use('dark_background')
fig = plt.figure(figsize=(16, 10))
gs = fig.add_gridspec(2, 2)

# 1. Gráfico de Vibración con Zonas
ax1 = fig.add_subplot(gs[0, :])
ax1.plot(df['Hora'], df['Vibracion_Hz'], color='cyan', lw=2, label='Vibración (Hz)')
ax1.axhspan(0, 35, color='green', alpha=0.2, label='Zona Normal')
ax1.axhspan(35, 70, color='yellow', alpha=0.2, label='Zona Desgaste')
ax1.axhspan(70, 120, color='red', alpha=0.2, label='Zona Crítica')
ax1.set_title("MONITOREO DE VIBRACIÓN EN TIEMPO REAL", fontsize=15)
ax1.legend(loc='upper left')

# 2. Análisis de Tendencia (Media Móvil)
df['Media_Movil'] = df['Vibracion_Hz'].rolling(window=5).mean()
ax1.plot(df['Hora'], df['Media_Movil'], color='white', linestyle='--', label='Tendencia (MA5)')

# 3. Distribución de Estados (Pie Chart)
ax2 = fig.add_subplot(gs[1, 0])
counts = df['Estado_Real'].value_counts()
ax2.pie([counts.get(i, 0) for i in range(3)], labels=modelo.estados,
        colors=['#2ecc71', '#f1c40f', '#e74c3c'], autopct='%1.1f%%')
ax2.set_title("Distribución de Salud Operativa")



# 4. Semáforo de Salud y Reporte
ax3 = fig.add_subplot(gs[1, 1])
ax3.axis('off')
ultima_vib = df['Vibracion_Hz'].iloc[-1]
status_color = 'Buena' if ultima_vib < 40 else 'Regular' if ultima_vib < 70 else 'Mala'

reporte = (
    f"REPORTE DE SALUD INDUSTRIAL\n"
    f"{'='*30}\n"
    f"Status: {status_color}\n"
    f"Vibración Actual: {ultima_vib:.2f} Hz\n"
    f"Vida Útil Restante (RUL): {max(0, int(rul))} hrs\n"
    f"Costo Estimado de Falla: ${df['Estado_Real'].sum() * 500} USD\n"
    f"{'='*30}\n"
    f"RECOMENDACIÓN:\n"
    f"{'Revisión inmediata' if status_color == '🔴' else 'Lubricación programada' if status_color == '🟡' else 'Mantener operación'}"
)
ax3.text(0.1, 0.5, reporte, fontsize=14, family='monospace', bbox=dict(facecolor='grey', alpha=0.2))


# --- GENERACIÓN DEL MAPA DE CALOR DE VALIDACIÓN ---

def graficar_validacion(df, modelo):
    plt.style.use('default') # Volvemos a estilo claro para mejor lectura de etiquetas
    plt.figure(figsize=(6, 4))

    # Creamos la tabla cruzada entre Realidad y Sensor
    # Convertimos los índices numéricos a nombres para que sea legible
    real_nombres = [modelo.estados[i] for i in df['Estado_Real']]
    sensor_nombres = [modelo.obs_nombres[i] for i in df['Obs_Idx']]

    matriz_confusion = pd.crosstab(
        pd.Series(real_nombres, name='ESTADO REAL (OCULTO)'),
        pd.Series(sensor_nombres, name='DETECCIÓN SENSOR (OBSERVACIÓN)'),
        normalize='index' # Esto nos da porcentajes, útil para validación
    )

    # Dibujar el Mapa de Calor
    sns.heatmap(matriz_confusion, annot=True, fmt=".2%", cmap="YlOrRd", cbar_kws={'label': 'Probabilidad de Coincidencia'})

    plt.title("MATRIZ DE VALIDACIÓN HMM\n(¿Qué tan bien el sensor representa la realidad?)", fontsize=14, pad=20)
    plt.show()

# Llamamos a la función con los datos de tu última simulación
graficar_validacion(df, modelo)


plt.tight_layout()
plt.show()